export default {
  loading: require(`../assets/images/loading.gif`),
  particle: require(`../assets/images/particle.png`),
  'music-toggle': require(`../assets/images/music-toggle.png`),
  promo: require(`../assets/images/promo.png`),
  retro_last_title: require(`../assets/images/retro_last_title.png`),
  retro_subtitle: require(`../assets/images/retro_subtitle.png`),
  retro_title: require(`../assets/images/retro_title.png`),
  sky: require(`../assets/images/sky.png`),
  backgrounds: {
    beach: require(`../assets/images/backgrounds/beach.png`),
    charlie_full: require(`../assets/images/backgrounds/charlie_full.png`),
    charlie_shadow: require(`../assets/images/backgrounds/charlie_shadow.png`),
    dark: require(`../assets/images/backgrounds/dark.png`),
    sunset: require(`../assets/images/backgrounds/sunset.png`),
    xamaronia: require(`../assets/images/backgrounds/xamaronia.png`),
  },
  characters: {
    brent: require(`../assets/images/characters/brent.png`),
    charlie: require(`../assets/images/characters/charlie.png`),
    nik: require(`../assets/images/characters/nik.png`),
    vscodet: require(`../assets/images/characters/vscodet.png`),
    xaml: require(`../assets/images/characters/xaml.png`),
  },
};
